// Shared monorepo ESLint config — but the per-contract subdirectories under
// `src/` are generated by `stellar contract bindings typescript` and are not
// linted (the generator emits code that doesn't satisfy our strict rules).
// Only the hand-written barrel (`src/index.ts`) is linted.
import shared from "@kaido/config/eslint";

export default [
  { ignores: ["src/*/**"] },
  ...(Array.isArray(shared) ? shared : [shared]),
];
